version: 0.0
os: linux
files:
  - source: /test1.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencie.sh
      timeout: 300
      runas: root
    - location: scripts/start_serve.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_serve.sh
      timeout: 300
      runas: root
